import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Copy, Download, Share2 } from 'lucide-react';

interface ResultDisplayProps {
  content: string;
}

export const ResultDisplay: React.FC<ResultDisplayProps> = ({ content }) => {
  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    alert('Sermon note copied to clipboard!');
  };

  if (!content) return null;

  return (
    <div className="bg-white rounded-xl shadow-lg border border-stone-200 overflow-hidden animate-fade-in-up mt-8">
      <div className="bg-stone-50 border-b border-stone-200 px-6 py-4 flex items-center justify-between">
        <h2 className="font-bold text-stone-700">Sermon Note</h2>
        <div className="flex space-x-2">
          <button 
            onClick={handleCopy}
            className="p-2 text-stone-500 hover:text-stone-800 hover:bg-stone-200 rounded-full transition-colors"
            title="Copy to clipboard"
          >
            <Copy size={18} />
          </button>
          <button className="p-2 text-stone-500 hover:text-stone-800 hover:bg-stone-200 rounded-full transition-colors" title="Download (Demo)">
            <Download size={18} />
          </button>
        </div>
      </div>
      <div className="p-8 sm:p-10 prose prose-stone prose-headings:font-serif prose-p:leading-relaxed prose-li:leading-relaxed max-w-none">
        <ReactMarkdown
            components={{
                h1: ({node, ...props}) => <h1 className="text-3xl font-serif text-stone-900 mb-6 border-b pb-4" {...props} />,
                h2: ({node, ...props}) => <h2 className="text-xl font-bold text-stone-800 mt-8 mb-4 flex items-center" {...props} />,
                strong: ({node, ...props}) => <strong className="font-bold text-stone-900 bg-stone-100 px-1 rounded" {...props} />,
                ul: ({node, ...props}) => <ul className="list-disc list-outside ml-5 space-y-2" {...props} />,
                blockquote: ({node, ...props}) => <blockquote className="border-l-4 border-stone-300 pl-4 py-2 italic bg-stone-50 rounded-r text-stone-600" {...props} />,
            }}
        >
            {content}
        </ReactMarkdown>
      </div>
      <div className="bg-stone-50 p-6 border-t border-stone-200 text-center text-sm text-stone-500 italic">
        Generated by AI based on homiletic principles. Please review and pray over this content before use.
      </div>
    </div>
  );
};
